
- name: Generate Helm Chart Values From Template
  become: yes
  template:
    src: values.yml.j2
    dest: /tmp/nvidia_values.yml
    mode: 0644
  when: inventory_hostname == groups[rke2_servers_group_name].0

- name: Add NVIDIA Helm repository
  kubernetes.core.helm_repository:
    name: nvidia
    repo_url: "https://helm.ngc.nvidia.com/nvidia"
  when: inventory_hostname == groups[rke2_servers_group_name].0

- name: Install NVIDIA 
  kubernetes.core.helm:
    name: gpu-operator
    chart_ref: nvidia/gpu-operator
    chart_version: "{{ nvidia.version }}"
    namespace: "{{ nvidia.namespace }}"
    create_namespace: yes
    update_repo_cache: True
    wait: yes
    values_files:
      - /tmp/nvidia_values.yml
    values: "{{ nvidia.helm_values }}"
  when: inventory_hostname == groups[rke2_servers_group_name].0