- name: Merge custom configs
  set_fact:
    storage: "{{ rook | combine(config | default({}), recursive=True) }}"

- name: Install Rook
  include_tasks: install.yml
  when:
    - cmd == "install"
    - inventory_hostname in groups[rke2_servers_group_name]

- name: Add Rook-Ceph PSA Exemptions
  set_fact:
    psa:
      defaults: "{{ psa.defaults }}"
      exemptions:
        usernames: "{{ psa.exemptions.usernames }}"
        runtimeClasses: "{{ psa.exemptions.runtimeClasses}}"
        namespaces: "{{ psa.exemptions.namespaces + [storage.namespace] }}"
  when: 
    - cmd == "psa"
    - psa is defined
    - inventory_hostname in groups[rke2_servers_group_name]

- name: Uh oh!
  debug:
    msg: "No command provided to rook-ceph role."
  when: cmd == ""
