- name: Merge custom configs
  set_fact:
    postgres: "{{ cnpg | combine(config | default({}), recursive=True) }}"
  
- name: Install CNPG
  include_tasks: install.yml
  when:
    - cmd == "install"
    - inventory_hostname in groups[rke2_servers_group_name]

- name: Create PostgreSQL Database in CNPG
  include_role:
    name: cnpg-db
  when:
    - cmd == "provision"
    - inventory_hostname in groups[rke2_servers_group_name]

- name: Add CNPG PSA Exemption
  set_fact:
    psa:
      defaults: "{{ psa.defaults }}"
      exemptions:
        usernames: "{{ psa.exemptions.usernames }}"
        runtimeClasses: "{{ psa.exemptions.runtimeClasses}}"
        namespaces: "{{ psa.exemptions.namespaces + [postgres.namespace] }}"
  when: 
    - psa is defined
    - cmd == "psa"
    - inventory_hostname in groups[rke2_servers_group_name]

- name: Uh oh!
  debug:
    msg: "No command provided to cnpg role."
  when: cmd == ""

