- name: Copy default values.yml to /tmp
  copy:
    src: values.yml
    dest: /tmp/certmanager_values.yml
  when: 
    - inventory_hostname == groups[rke2_servers_group_name].0

- name: Add certmanager chart repo
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: "https://charts.jetstack.io"
  when: 
    - inventory_hostname == groups[rke2_servers_group_name].0

- name: Install the certmanager Helm chart
  kubernetes.core.helm:
    name: cert-manager
    chart_ref: jetstack/cert-manager
    chart_version: "{{ certmanager.version }}"
    namespace: "{{ certmanager.namespace }}"
    create_namespace: yes
    update_repo_cache: True
    wait: yes
    values_files:
      - /tmp/certmanager_values.yml
    values: "{{ certmanager.helm_values }}"
  register: helm_install_result
  when:
    - inventory_hostname == groups[rke2_servers_group_name].0

- name: Display Helm install result
  debug:
    var: helm_install_result
  when: 
    - inventory_hostname == groups[rke2_servers_group_name].0

- name: Provision Certificates
  include_tasks: refresh_pki.yml
  when:
    - inventory_hostname in groups[rke2_servers_group_name]