- name: Merge custom configs
  set_fact:
    certmanager: "{{ certmanager | combine(config | default({}), recursive=True) }}"

- name: Add Cert Manager PSA Exemption
  set_fact:
    psa:
      defaults: "{{ psa.defaults }}"
      exemptions:
        usernames: "{{ psa.exemptions.usernames }}"
        runtimeClasses: "{{ psa.exemptions.runtimeClasses}}"
        namespaces: "{{ psa.exemptions.namespaces + [certmanager.namespace] }}"
  when: 
    - psa is defined
    - cmd == "psa"
    - inventory_hostname in groups[rke2_servers_group_name]

- name: Install Cert Manager
  include_tasks: install.yml
  when:
    - cmd == "install"
    - inventory_hostname in groups[rke2_servers_group_name]
  
- name: Refresh PKI
  include_tasks: refresh_pki.yml
  when:
    - cmd == "provision"
    - inventory_hostname in groups[rke2_servers_group_name]

- name: Uh oh!
  debug:
    msg: "No command provided to certmanger role."
  when: cmd == ""