vmcluster2:
  vars:
    rke2_cluster_group_name: vmcluster2
    rke2_servers_group_name: servers
    rke2_agents_group_name: agents
  children:
    servers:
      hosts:
        vm4:
          ansible_host: 192.168.122.101 
          rke2_type: server
          os_role: ubuntu 
        vm5:
          ansible_host: 192.168.122.102
          rke2_type: server
          os_role: ubuntu 
        vm6:
          ansible_host: 192.168.122.103
          rke2_type: server
          os_role: ubuntu 
