
- name: Add Bitnami repo for Loki
  kubernetes.core.helm_repository:
    name: bitnami
    repo_url: "https://charts.bitnami.com/bitnami"
  when: 
    - inventory_hostname == groups[rke2_servers_group_name].0

- name: Install Loki 
  kubernetes.core.helm:
    name: loki
    chart_ref: bitnami/grafana-loki
    chart_version: "{{ loki.version }}"
    namespace: "{{ loki.namespace }}"
    wait: yes
    timeout: 600s
    create_namespace: yes
    values: "{{ loki.helm_values }}"
  when: 
    - inventory_hostname == groups[rke2_servers_group_name].0

- name: Create Loki Cluster Output for Rancher Logging
  k8s:
    state: present
    definition:
      apiVersion: logging.banzaicloud.io/v1beta1
      kind: ClusterOutput
      metadata:
        name: loki-logging-output
        namespace: "{{ logging_namespace }}"
      spec:
        loki:
          url: "http://loki.{{ loki.namespace }}:3100" 
  when: 
    - inventory_hostname == groups[rke2_servers_group_name].0

- name: Add Loki as datasource to Grafana
  include_tasks:  loki_grafana.yml
  when: 
    - ranch.providers.monitoring.enabled
    - inventory_hostname == groups[rke2_servers_group_name].0