- name: Download Rancher CLI tarball 
  get_url:
    url: "https://github.com/rancher/cli/releases/download/{{ rancher.cli_version }}/rancher-linux-amd64-{{ rancher.cli_version }}.tar.gz"
    dest: "/tmp/rancher-linux-amd64-{{ rancher.cli_version }}.tar.gz"
    mode: '0755'

- name: Extract Rancher CLI tarball
  become: yes
  unarchive:
    src: "/tmp/rancher-linux-amd64-{{ rancher.cli_version }}.tar.gz"
    dest: "/tmp/"
    remote_src: yes

- name: Move rancher binary to /usr/local/bin
  become: yes
  command: mv /tmp/rancher-{{ rancher.cli_version }}/rancher /usr/local/bin/
  args:
    creates: /usr/local/bin/rancher

- name: Ensure rancher binary is executable
  become: yes
  file:
    path: /usr/local/bin/rancher
    mode: '0755'

- name: Login to Rancher
  include_tasks: login.yml