- name: Generate Helm Chart Values From Template
  template:
    src: values.yml.j2
    dest: /tmp/rancher_values.yml
  when: 
    - inventory_hostname == groups[rancher.cluster].0

- name: Add Rancher chart repos
  kubernetes.core.helm_repository:
    name: rancher-stable
    repo_url: "https://releases.rancher.com/server-charts/stable"
  when: 
    - inventory_hostname == groups[rancher.cluster].0

- name: Deploy Rancher using Helm
  kubernetes.core.helm:
    name: rancher
    chart_ref: rancher-stable/rancher
    chart_version: "{{ rancher.version }}"
    namespace: cattle-system
    create_namespace: yes
    update_repo_cache: True
    wait: yes
    values_files:
      - /tmp/rancher_values.yml
    values: "{{ rancher.helm_values }}"
  when: 
    - inventory_hostname == groups[rancher.cluster].0
  register: helm_install_result

- name: Display Helm install result
  debug:
    var: helm_install_result
  when: 
    - inventory_hostname == groups[rancher.cluster].0

- name: Add Rancher to /etc/hosts
  become: yes
  lineinfile:
    path: /etc/hosts
    regexp: '{{ rancher.hostname }}$'
    line: '{{ hostvars[groups[rancher.cluster].0] }} {{ rancher.hostname }}'
    state: present
  when: 
    - inventory_hostname in groups[rke2_servers_group_name]

- name: Update Rancher HTTPS Certificates
  include_tasks: update_certs.yml
  when: 
    - rancher.external_cert.enabled
    - inventory_hostname in groups[rancher.cluster]

- name: Install Rancher CLI
  import_tasks: install_cli.yml

- name: Set Rancher Server URL
  command: rancher settings set server-url 'https://{{ rancher.hostname }}'
  when: 
    - inventory_hostname == groups[rancher.cluster].0

- name: Herd Ranch 
  import_tasks: herd-ranch.yml
  when: 
    - inventory_hostname in groups[rke2_servers_group_name]

