- name: Merge custom configs
  set_fact:
    rancher: "{{ rancher | combine(config | default({}), recursive=True) }}"

- name: Install Rancher
  include_tasks: install.yml
  when:
    - cmd == "install"
    - inventory_hostname in groups[rke2_servers_group_name]

- name: Install Rancher CLI
  include_tasks: install_cli.yml
  when:
    - cmd == "install_cli"
    - inventory_hostname in groups[rke2_servers_group_name]

- name: Update Certs
  include_tasks: update_certs.yml
  when:
    - cmd == "certs"
    - inventory_hostname in groups[rancher.cluster]
    - inventory_hostname in groups[rke2_servers_group_name]

- name: Login to Rancher
  include_tasks: login.yml
  when: 
    - cmd == "login"
    - inventory_hostname in groups[rke2_servers_group_name]

- name: Join Clusters to Rancher
  include_tasks: herd-ranch.yml
  when: 
    - cmd == "herd"
    - inventory_hostname in groups[rke2_servers_group_name]

- name: Get Rancher IDs
  include_tasks: get_ids.yml
  when: 
    - cmd == "ids"
    - inventory_hostname in groups[rke2_servers_group_name]

- name: Add Rancher PSA Exemptions
  set_fact:
    psa:
      defaults: "{{ psa.defaults }}"
      exemptions:
        usernames: "{{ psa.exemptions.usernames }}"
        runtimeClasses: "{{ psa.exemptions.runtimeClasses}}"
        namespaces: "{{ psa.exemptions.namespaces + rancher_exemptions }}"
  when: 
    - cmd == "psa"
    - psa is defined
    - inventory_hostname in groups[rke2_servers_group_name]

- name: Uh oh!
  debug:
    msg: "No command provided to rancher role."
  when: cmd == ""
