vmcluster1:
  vars:
    rke2_cluster_group_name: vmcluster1
    rke2_servers_group_name: servers
    rke2_agents_group_name: agents
  children:
    servers:
      hosts:
        vm1:
          ansible_host: 192.168.122.101 
          rke2_type: server
          os_role: ubuntu 
        vm2:
          ansible_host: 192.168.122.102
          rke2_type: server
          os_role: ubuntu 
        vm3:
          ansible_host: 192.168.122.103
          rke2_type: server
          os_role: ubuntu 
