
- name: Generate Helm Chart Values From Template
  become: yes
  template:
    src: values.yml.j2
    dest: /tmp/monitor_values.yml
    mode: 0644
  when: inventory_hostname == groups[rke2_servers_group_name].0

- debug:
    var: rancher_cluster_id
  when: inventory_hostname == groups[rke2_servers_group_name].0
- debug:
    var: rancher_cluster_name
  when: inventory_hostname == groups[rke2_servers_group_name].0

- name: Add Rancher-Charts Helm repository
  kubernetes.core.helm_repository:
    name: rancher-charts
    repo_url: "https://charts.rancher.io"
  when: inventory_hostname == groups[rke2_servers_group_name].0

- name: Install Rancher Monitoring CRDs
  kubernetes.core.helm:
    name: rancher-monitoring-crd
    chart_ref: rancher-charts/rancher-monitoring-crd
    chart_version: "{{ monitoring.crd.version }}"
    namespace: "{{ monitoring.namespace }}"
    create_namespace: yes
    update_repo_cache: True
    wait: yes
    values: "{{ monitoring.crd.helm_values }}"
  when: inventory_hostname == groups[rke2_servers_group_name].0

- name: Install the Rancher Monitoring Helm chart
  kubernetes.core.helm:
    name: rancher-monitoring
    chart_ref: rancher-charts/rancher-monitoring
    chart_version: "{{ monitoring.version }}"
    namespace: "{{ monitoring.namespace }}"
    wait: yes
    values_files:
      - /tmp/monitor_values.yml
    values: "{{ monitoring.helm_values }}"
  when: inventory_hostname == groups[rke2_servers_group_name].0
